version: 0.0
os: linux
files:
  - source: /
    destination: /opt/slack-bot
permissions:
  - object: /opt/slack-bot/scripts
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
