version: 0.0
os: linux
files:
  - source: /
    destination: /opt/slack-bot
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
